image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: registry.gitlab.com/Amore52/mvp_business
  IMAGE_TAG: latest

stages:
  - test
  - build
  - deploy

# --- Stage: test ---
test_job:
  image: python:3.13
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m pytest
  artifacts:
    paths:
      - __pycache__/
      - .pytest_cache/

# --- Stage: build ---
build_job:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  only:
    - master

# --- Stage: deploy (пример с SSH) ---
deploy_job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - ssh user@yourserver "docker pull $IMAGE_NAME:$IMAGE_TAG && docker stop django-app || true"
    - ssh user@yourserver "docker rm django-app || true"
    - ssh user@yourserver "docker run -d --name django-app -p 8000:8000 $IMAGE_NAME:$IMAGE_TAG"
  only:
    - master
  when: manual